### ISSUE TITLE
Reinstalling octotree restarts computer

### ISSUE THREAD

**Issue by 1UnboundedSentience** [buunguyen/octotree#231]
I've used Octotree happily for months, but recently Octotree was suddenly disabled and it said I need to update permissions on chrome.  Renabling it caused my browser to crash.  I uninstalled it and tried to reinstall, but clicking "add to chrome" on the chrome web store causes my computer to restart and all applications to close as well.

**Comment by buunguyen** [comment]
The new permission is required because Octotree now supports GitLab, so it needs permission for gitlab.com. I don't know why it causes your machine to restart, certainly don't have that problem myself and already checked with a few others, none having seen the issue.

Can you specify the OS and Chrome version you're using?

**Comment by buunguyen** [comment]
Close due to inactivity. If the the problem persists, please file another issue and provide the requested information.
