### ISSUE TITLE
Safari Extensions Certificate

### ISSUE THREAD

**Issue by PhamBaTho** [buunguyen/octotree#269]
How can I keep Octotree after I restart Safari? Please see this warning screenshot after I pressed Install in Show Extension Builder?

<img width="702" alt="screen shot 2016-02-25 at 5 23 00 pm" src="https://cloud.githubusercontent.com/assets/5548600/13316879/a3ea8c42-dbe4-11e5-9edc-4d21230e4e22.png">

**Comment by irliao** [comment]
@PhamBaTho Correct me if I am wrong, but I believe you need to enroll in the Apple Developer Member ($100.00/year) program in order to generate yourself a Safari Extension Certificate which allows you to Build Packages and Install packages that persists after Safari restarts. Not sure if there is other ways.

Source: https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionsOverview/ExtensionsOverview.html#//apple_ref/doc/uid/TP40009977-CH15-SW26

Btw, Safari does not seem to recognize/detect certificates on OSX 10.11.3. So if you do buy the membership you can download 10.11.4 beta, which will work.

**Comment by PhamBaTho** [comment]
@irliao thanks for clear explanation. I'm moving to Chrome now, much more supported extension
