### ISSUE TITLE
Sidebar below title bar

### ISSUE THREAD

**Issue by cooldroid7** [buunguyen/octotree#412]
#### Description
Is it possible to shift the sidebar so that it starts below GitHub's title bar?
The other possibility is to have the sidebar header colored same as the GitHub's title bar (I already see this happening in the screenshot in README, but doesn't work for me).

#### Environment
* Octotree version: 2.1.0
* Browser & version: Chrome 59.0.3071.109 (Official Build) (64-bit)
* OS & version: Windows 10

![image](https://user-images.githubusercontent.com/20253275/27514968-735c6c0c-59b6-11e7-90eb-44b48bf92c21.png)

**Comment by morkro** [comment]
I am also interested in the black title bar, as shown in the README.

**Comment by piranna** [comment]
Any update on this?

**Comment by crashbell** [comment]
#441 is to update the README's screenshots to avoid any confusion. I tried to apply dark header and realized that it makes Octotree too visible to the rest since most of the time, people scroll down to view code so the consistency of header bars doesn't matter.

![dark header](https://user-images.githubusercontent.com/810139/30774748-f91910ec-a0b1-11e7-97b5-503eb447b080.png)

**Comment by buunguyen** [comment]
@crashbell good point. I agree. The black looks out of place in that screenshot. Close this ticket now.
