### ISSUE TITLE
Why did permissions change?

### ISSUE THREAD

**Issue by mjgs** [buunguyen/octotree#425]
I've had the extension installed for a while. Today I noticed it was disabled in Chrome, I had to accept new permissions to re-enable, read and write data. Surely it's only read data that is required?

**Comment by buunguyen** [comment]
The additional permission is for BitBucket support, see https://github.com/buunguyen/octotree/commit/770e1e145f4497a6ed5bceda1d8d94c925604efc#diff-2fd722e6b76fde5b7de39273197f4a4eR12.

**Comment by mjgs** [comment]
It's great that there is Bitbucket support now. I have a few more questions:

Why did this only disable in Chrome 3 months after the feature was merged?

From the docs:
> minimal requirement is `Repositories`'s `Read` permission

Why does the extension also require write permission in order for it to be enabled?

**Comment by buunguyen** [comment]
Because I just released yesterday. And there are 2 separate permission types, page vs GitHub API. 
 The extension requires page read/write (i.e. DOME, cookies, local storage) when the extension is on the domain (GitHub & BitBucket). But for GitHub, you have to explicitly grant the Repositories Read when setting the access token. They are separate permissions. Chrome doesn't control GitHub permission.

**Comment by mjgs** [comment]
Thanks for the clarification. I think the docs could be a little clearer, I wasn't aware about the different types of permissions.
